version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      DATABASE_URL: ${DATABASE_URL}  # Flask 連接 PostgreSQL
    volumes:
      - .:/app

  flyway:
    image: flyway/flyway:9
    restart: on-failure
    env_file:
      - .env.prod
    volumes:
      - ./sql/migrations:/flyway/sql
    environment:
      FLYWAY_URL: ${DATABASE_URL}  # 直接連接 Render PostgreSQL
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
